#!/bin/bash
# Linera Dominion - Remote Network Deployment Script
# This script deploys the Dominion MMORTS contracts to Linera testnet

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$PROJECT_DIR/target/wasm32-unknown-unknown/release"
FRONTEND_DIR="$PROJECT_DIR/frontend"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          LINERA DOMINION - TESTNET DEPLOYMENT             ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Configuration
LINERA_FAUCET=${LINERA_FAUCET:-"https://faucet.testnet.linera.net"}
LINERA_RPC=${LINERA_RPC:-"https://rpc.testnet.linera.net"}

echo -e "${YELLOW}Configuration:${NC}"
echo "  Faucet: $LINERA_FAUCET"
echo "  RPC: $LINERA_RPC"
echo ""

# Step 1: Check prerequisites
echo -e "${BLUE}[1/6] Checking prerequisites...${NC}"

if ! command -v linera &> /dev/null; then
    echo -e "${RED}Error: linera CLI not found${NC}"
    echo "Install it with: cargo install linera-service@0.15.8"
    exit 1
fi

if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites satisfied${NC}"

# Step 2: Build contracts if needed
echo ""
echo -e "${BLUE}[2/6] Building WASM contracts...${NC}"

if [ ! -f "$WASM_DIR/linera_dominion_contract.wasm" ] || [ "$1" == "--rebuild" ]; then
    cd "$PROJECT_DIR"
    cargo build --target wasm32-unknown-unknown --release
    echo -e "${GREEN}✓ Contracts built successfully${NC}"
else
    echo -e "${GREEN}✓ Using existing contract builds${NC}"
fi

# Step 3: Initialize wallet
echo ""
echo -e "${BLUE}[3/6] Initializing wallet...${NC}"

export LINERA_WALLET="$HOME/.linera-dominion/wallet.json"
export LINERA_STORAGE="rocksdb:$HOME/.linera-dominion/storage.db"

mkdir -p "$HOME/.linera-dominion"

if [ ! -f "$LINERA_WALLET" ] || [ "$1" == "--reset-wallet" ]; then
    echo "Requesting tokens from faucet..."
    linera wallet init --faucet "$LINERA_FAUCET" --with-new-chain
    echo -e "${GREEN}✓ Wallet initialized${NC}"
else
    echo -e "${GREEN}✓ Using existing wallet${NC}"
fi

# Get chain ID
CHAIN_ID=$(linera wallet show | grep "Default Chain" | awk '{print $NF}')
echo "  Chain ID: $CHAIN_ID"

# Step 4: Deploy Dominion Application
echo ""
echo -e "${BLUE}[4/6] Deploying Dominion (User Chain) application...${NC}"

DOMINION_APP=$(linera publish-and-create \
    "$WASM_DIR/linera_dominion_contract.wasm" \
    "$WASM_DIR/linera_dominion_service.wasm" \
    --json-parameters '{
        "home_x": 100,
        "home_y": 200,
        "starting_iron": 10000,
        "starting_deuterium": 5000,
        "starting_crystals": 2500,
        "universe_seed": 12345
    }' 2>&1 | tail -1)

echo -e "${GREEN}✓ Dominion App ID: $DOMINION_APP${NC}"

# Step 5: Deploy Region Application
echo ""
echo -e "${BLUE}[5/6] Deploying Region Chain application...${NC}"

REGION_APP=$(linera publish-and-create \
    "$WASM_DIR/linera_dominion_region_contract.wasm" \
    "$WASM_DIR/linera_dominion_region_service.wasm" \
    --json-parameters '{
        "sector_x": 0,
        "sector_y": 0,
        "universe_seed": 12345
    }' 2>&1 | tail -1)

echo -e "${GREEN}✓ Region App ID: $REGION_APP${NC}"

# Step 6: Deploy Battle Application
echo ""
echo -e "${BLUE}[6/6] Deploying Battle Chain application...${NC}"

BATTLE_APP=$(linera publish-and-create \
    "$WASM_DIR/linera_dominion_battle_contract.wasm" \
    "$WASM_DIR/linera_dominion_battle_service.wasm" \
    --json-parameters "{
        \"region_chain\": \"$CHAIN_ID\",
        \"position_x\": 50,
        \"position_y\": 50,
        \"max_turns\": 10,
        \"turn_timeout_secs\": 60
    }" 2>&1 | tail -1)

echo -e "${GREEN}✓ Battle App ID: $BATTLE_APP${NC}"

# Generate .env file for frontend
echo ""
echo -e "${BLUE}Generating frontend configuration...${NC}"

cat > "$FRONTEND_DIR/.env.local" << EOF
# Auto-generated by deploy-testnet.sh
# Generated at: $(date)

NEXT_PUBLIC_LINERA_GRAPHQL=$LINERA_RPC
NEXT_PUBLIC_LINERA_FAUCET=$LINERA_FAUCET
NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_DOMINION_APP_ID=$DOMINION_APP
NEXT_PUBLIC_REGION_APP_ID=$REGION_APP
NEXT_PUBLIC_BATTLE_APP_ID=$BATTLE_APP
EOF

echo -e "${GREEN}✓ Frontend .env.local created${NC}"

# Summary
echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              DEPLOYMENT COMPLETE! 🚀                      ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
echo -e "${YELLOW}Application IDs:${NC}"
echo "  Dominion: $DOMINION_APP"
echo "  Region:   $REGION_APP"
echo "  Battle:   $BATTLE_APP"
echo ""
echo -e "${YELLOW}Chain ID:${NC} $CHAIN_ID"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. cd frontend && npm install"
echo "  2. npm run dev  (for local testing)"
echo "  3. vercel       (to deploy to Vercel)"
echo ""
echo -e "${YELLOW}GraphQL Endpoints:${NC}"
echo "  Dominion: $LINERA_RPC/chains/$CHAIN_ID/applications/$DOMINION_APP"
echo "  Region:   $LINERA_RPC/chains/$CHAIN_ID/applications/$REGION_APP"
echo "  Battle:   $LINERA_RPC/chains/$CHAIN_ID/applications/$BATTLE_APP"
echo ""
